package com.uhere.auto.entity;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * TblGec generated by hbm2java
 */
@Entity
@Cacheable(true)
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY,region="eternal")
@Table(name = "TBL_COMBUSTIVEL", catalog = "uherebd")
public class TblCombustivel implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "chave",unique = true, nullable = false,insertable=false,updatable=false)
	private Long chave = 0L;
	
	@Column(name = "descricao",unique = false, nullable = false,insertable=false,updatable=false)
	private String descricao;

	public TblCombustivel() {
		super();
	}

	public TblCombustivel(Long chave) {
		super();
		this.chave = chave;
	}
	
	public TblCombustivel(Long chave, String descricao) {
		super();
		this.chave = chave;
		this.descricao = descricao;
	}

	public Long getChave() {
		return chave;
	}

	public void setChave(Long chave) {
		this.chave = chave;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chave == null) ? 0 : chave.hashCode());
		result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TblCombustivel other = (TblCombustivel) obj;
		if (chave == null) {
			if (other.chave != null)
				return false;
		} else if (!chave.equals(other.chave))
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TblCombustivel [chave=" + chave + ", descricao=" + descricao + "]";
	}
	
}
