package com.uhere.auto.entity;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TblGec generated by hbm2java
 */
@Entity
@Cacheable(true)
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY,region="eternal")
@Table(name = "TBL_MODELO", catalog = "uherebd")
public class TblModelo implements java.io.Serializable {

	private static final long serialVersionUID = -6333930167694470564L;

	@Id
	@Column(name = "chave", unique = true, nullable = false,insertable=false,updatable=false)
	private Long chave;
	
	@Column(name = "descricao", length = 20, unique = false, nullable = false,insertable=false,updatable=false)
	private String descricao;
	
	@JsonIgnore
	@ManyToOne(optional = false,fetch = FetchType.LAZY)
	@JoinColumn(name = "marca",updatable = false, insertable = false)
	@Fetch(FetchMode.SELECT)
	private TblMarca tblMarca;

	
	public TblModelo() {
		super();
	}

	public TblModelo(Long chave, String descricao, TblMarca tblMarca) {
		super();
		this.chave = chave;
		this.descricao = descricao;
		this.tblMarca = tblMarca;
	}

	public Long getChave() {
		return chave;
	}

	public void setChave(Long chave) {
		this.chave = chave;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public TblMarca getTblMarca() {
		return tblMarca;
	}

	public void setTblMarca(TblMarca tblMarca) {
		this.tblMarca = tblMarca;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (chave ^ (chave >>> 32));
		result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
		result = prime * result + ((tblMarca == null) ? 0 : tblMarca.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TblModelo other = (TblModelo) obj;
		if (chave != other.chave)
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		if (tblMarca == null) {
			if (other.tblMarca != null)
				return false;
		} else if (!tblMarca.equals(other.tblMarca))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TblModelo [chave=" + chave + ", descricao=" + descricao + ", tblMarca=" + tblMarca + "]";
	}
}
