package com.uhere.auto.entity;

import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TblGec generated by hbm2java
 */
@Entity
@Cacheable(true)
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY,region="eternal")
@Table(name = "TBL_OPCIONAIS", catalog = "uherebd")
public class TblOpcionais implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "chave", unique = true, nullable = false,insertable=false,updatable=false)
	private Long chave = 0L;
	
	@Column(name = "descricao", length = 20, unique = false, nullable = false,insertable=false,updatable=false)
	private String descricao;
	
	@ManyToMany(mappedBy = "tblOpcionais",fetch=FetchType.LAZY)
	@Fetch(FetchMode.SELECT)
	private List<TblVeiculo> tblVeiculos;

	public TblOpcionais() {
		super();
	}

	public TblOpcionais(Long chave) {
		super();
		this.chave = chave;
	}

	public TblOpcionais(Long chave, String descricao, List<TblVeiculo> tblVeiculos) {
		super();
		this.chave = chave;
		this.descricao = descricao;
		this.tblVeiculos = tblVeiculos;
	}

	public Long getChave() {
		return chave;
	}

	public void setChave(Long chave) {
		this.chave = chave;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public List<TblVeiculo> getTblVeiculos() {
		return tblVeiculos;
	}

	public void setTblVeiculos(List<TblVeiculo> tblVeiculos) {
		this.tblVeiculos = tblVeiculos;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chave == null) ? 0 : chave.hashCode());
		result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
		result = prime * result + ((tblVeiculos == null) ? 0 : tblVeiculos.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TblOpcionais other = (TblOpcionais) obj;
		if (chave == null) {
			if (other.chave != null)
				return false;
		} else if (!chave.equals(other.chave))
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		if (tblVeiculos == null) {
			if (other.tblVeiculos != null)
				return false;
		} else if (!tblVeiculos.equals(other.tblVeiculos))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TblOpcionais [chave=" + chave + ", descricao=" + descricao + ", tblVeiculos=" + tblVeiculos + "]";
	}
}
