package com.uhere.auto.entity;

import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.springframework.security.core.GrantedAuthority;

/**
 * TblGec generated by hbm2java
 */
@Entity
@Cacheable(true)
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY,region="eternal")
@Table(name = "TBL_PERMISSOES", catalog = "uherebd")
public class TblPermissoes implements java.io.Serializable,GrantedAuthority {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "chave",length = 1, unique = true, nullable = false,insertable=false,updatable=false)
	private char chave ;
	
	@Column(name = "descricao",length = 25, unique = false, nullable = false,insertable=false,updatable=false)
	private String descricao;
	
	@ManyToMany(mappedBy = "tblPermissoes",cascade=CascadeType.PERSIST,fetch=FetchType.LAZY)
	@Fetch(FetchMode.JOIN)
	private List<TblUsuario> tblUsuarios;

	public TblPermissoes() {
		super();
	}

	public TblPermissoes(char chave, String descricao, List<TblUsuario> tblUsuarios) {
		super();
		this.chave = chave;
		this.descricao = descricao;
		this.tblUsuarios = tblUsuarios;
	}

	public char getChave() {
		return chave;
	}

	public void setChave(char chave) {
		this.chave = chave;
	}

	public String getDescricao() {
		return descricao;
	}
	
	@Override
	public String getAuthority() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public List<TblUsuario> getTblUsuarios() {
		return tblUsuarios;
	}

	public void setTblUsuarios(List<TblUsuario> tblUsuarios) {
		this.tblUsuarios = tblUsuarios;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + chave;
		result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
		result = prime * result + ((tblUsuarios == null) ? 0 : tblUsuarios.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TblPermissoes other = (TblPermissoes) obj;
		if (chave != other.chave)
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		if (tblUsuarios == null) {
			if (other.tblUsuarios != null)
				return false;
		} else if (!tblUsuarios.equals(other.tblUsuarios))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TblPermissoes [chave=" + chave + ", descricao=" + descricao + ", tblUsuarios=" + tblUsuarios + "]";
	}
}
