package com.uhere.auto.entity;

import java.util.List;

import javax.persistence.Cacheable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * TblGec generated by hbm2java
 */
@Entity
@Cacheable(true)
@Cache(usage=CacheConcurrencyStrategy.READ_ONLY,region="eternal")
@Table(name = "TBL_UF", catalog = "uherebd")
public class TblUf implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "chave", unique = true, nullable = false, length = 2, updatable=false, insertable=false)
	private String chave;
	
	@Column(name = "descricao",unique = false, nullable = false, length = 40, updatable=false, insertable=false)
	private String descricao;

	@OneToMany(cascade=CascadeType.REFRESH, mappedBy="tblUf",fetch=FetchType.LAZY)
	@Fetch(FetchMode.SELECT)
	private List<TblCidade> tblCidades;

	public TblUf() {
		super();
	}

	public TblUf(String chave) {
		super();
		this.chave = chave;
	}

	public TblUf(String chave, String descricao, List<TblCidade> tblCidades) {
		super();
		this.chave = chave;
		this.descricao = descricao;
		this.tblCidades = tblCidades;
	}

	public String getChave() {
		return chave;
	}

	public void setChave(String chave) {
		this.chave = chave;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public List<TblCidade> getTblCidades() {
		return tblCidades;
	}

	public void setTblCidades(List<TblCidade> tblCidades) {
		this.tblCidades = tblCidades;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chave == null) ? 0 : chave.hashCode());
		result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
		result = prime * result + ((tblCidades == null) ? 0 : tblCidades.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TblUf other = (TblUf) obj;
		if (chave == null) {
			if (other.chave != null)
				return false;
		} else if (!chave.equals(other.chave))
			return false;
		if (descricao == null) {
			if (other.descricao != null)
				return false;
		} else if (!descricao.equals(other.descricao))
			return false;
		if (tblCidades == null) {
			if (other.tblCidades != null)
				return false;
		} else if (!tblCidades.equals(other.tblCidades))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "TblUf [chave=" + chave + ", descricao=" + descricao + ", tblCidades=" + tblCidades + "]";
	}
}
